#!/bin/bash

# ERP System Production Setup Script
# Requirements: docker-compose.prod.yml + this file only

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_status()  { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error()   { echo -e "${RED}[ERROR]${NC} $1"; }

COMPOSE_FILE="docker-compose.prod.yml"

# Check prerequisites
check_prerequisites() {
    print_status "Checking prerequisites..."

    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed. Please install Docker first."
        exit 1
    fi

    if ! docker compose version &> /dev/null; then
        print_error "Docker Compose is not available. Please install Docker Compose."
        exit 1
    fi

    if [ ! -f "$COMPOSE_FILE" ]; then
        print_error "$COMPOSE_FILE not found in current directory."
        exit 1
    fi

    print_success "Prerequisites check passed"
}

# Generate a random secret
generate_secret() {
    node -e "console.log(require('crypto').randomBytes(64).toString('hex'))" 2>/dev/null \
        || openssl rand -hex 64 2>/dev/null \
        || cat /dev/urandom | tr -dc 'a-f0-9' | head -c 128
}

# Generate a random password
generate_password() {
    openssl rand -base64 16 2>/dev/null \
        || cat /dev/urandom | tr -dc 'A-Za-z0-9!@#$%' | head -c 16
}

# Setup .env file
setup_environment() {
    if [ -f .env ]; then
        print_warning ".env file already exists. Skipping environment setup."
        return
    fi

    print_status "Setting up environment configuration..."
    echo ""
    echo "Press ENTER to use the auto-generated value, or type your own."
    echo ""

    # Domain
    read -p "  Domain / server IP (e.g. https://erp.example.com): " INPUT_DOMAIN
    DOMAIN=${INPUT_DOMAIN:-http://localhost}

    # Database password
    DEFAULT_DB_PASS=$(generate_password)
    read -p "  Database password [auto: $DEFAULT_DB_PASS]: " INPUT_DB_PASS
    DB_PASS=${INPUT_DB_PASS:-$DEFAULT_DB_PASS}

    # Redis password
    DEFAULT_REDIS_PASS=$(generate_password)
    read -p "  Redis password [auto: $DEFAULT_REDIS_PASS]: " INPUT_REDIS_PASS
    REDIS_PASS=${INPUT_REDIS_PASS:-$DEFAULT_REDIS_PASS}

    # JWT secret
    DEFAULT_JWT_SECRET=$(generate_secret)
    read -p "  JWT secret [auto-generated, press ENTER]: " INPUT_JWT_SECRET
    JWT_SECRET=${INPUT_JWT_SECRET:-$DEFAULT_JWT_SECRET}

    echo ""

    cat > .env <<EOF
# Generated by setup.sh on $(date)

# Application
NODE_ENV=production
PORT=3001

# Database
DATABASE_HOST=postgres
DATABASE_PORT=5432
DATABASE_NAME=erp_db
DATABASE_USERNAME=erp_user
DATABASE_PASSWORD=${DB_PASS}
DATABASE_LOGGING=false
DATABASE_SYNCHRONIZE=false
DATABASE_SSL=false

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=${REDIS_PASS}
REDIS_DB=0
REDIS_TTL=3600

# JWT
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d
JWT_AUDIENCE=erp-app
JWT_ISSUER=erp-backend

# Security
ALLOWED_ORIGINS=${DOMAIN}
FRONTEND_URL=${DOMAIN}
CSP_REPORT_ONLY=false
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX=100
HSTS_MAX_AGE=31536000
HSTS_INCLUDE_SUBDOMAINS=true
HSTS_PRELOAD=true

# Logging
LOG_LEVEL=warn
LOG_FORMAT=combined
ENABLE_REQUEST_LOGGING=true
ENABLE_METRICS=false
ENABLE_SWAGGER=false
DEBUG_MODE=false
EOF

    print_success ".env file created"
}

# Create required directories
create_directories() {
    print_status "Creating required directories..."
    mkdir -p data/postgres data/redis uploads logs backups
    print_success "Directories created"
}

# Pull and start services
deploy_services() {
    print_status "Pulling images..."
    docker compose -f "$COMPOSE_FILE" pull

    print_status "Starting services..."
    docker compose -f "$COMPOSE_FILE" up -d
    print_success "Services started"
}

# Wait for backend health
wait_for_services() {
    print_status "Waiting for services to be ready..."

    print_status "Waiting for backend..."
    until curl -sf http://localhost:3001/api/health > /dev/null 2>&1; do
        sleep 5
    done

    print_success "All services are ready"
}

# Show status
show_status() {
    docker compose -f "$COMPOSE_FILE" ps

    echo ""
    print_success "ERP System deployed successfully!"
    echo ""
    echo "Access: ${DOMAIN:-http://localhost}"
    echo ""
    echo "Default credentials:"
    echo "  Username: admin"
    echo "  Password: Admin@123!"
    echo "  ** Change password immediately after first login! **"
    echo ""
    echo "Useful commands:"
    echo "  View logs:    docker compose -f $COMPOSE_FILE logs -f"
    echo "  Restart:      docker compose -f $COMPOSE_FILE restart"
    echo "  Stop:         docker compose -f $COMPOSE_FILE down"
    echo "  Status:       docker compose -f $COMPOSE_FILE ps"
    echo ""
}

cleanup_on_error() {
    print_error "Setup failed. Stopping services..."
    docker compose -f "$COMPOSE_FILE" down
    exit 1
}

trap cleanup_on_error ERR

# Main
echo "==============================================="
echo "   ERP System - Production Setup Script"
echo "==============================================="
echo ""

case "${1:-setup}" in
    "setup")
        check_prerequisites
        setup_environment
        create_directories
        deploy_services
        wait_for_services
        show_status
        ;;
    "start")
        docker compose -f "$COMPOSE_FILE" up -d
        ;;
    "stop")
        docker compose -f "$COMPOSE_FILE" down
        ;;
    "restart")
        docker compose -f "$COMPOSE_FILE" restart
        ;;
    "logs")
        docker compose -f "$COMPOSE_FILE" logs -f
        ;;
    "status")
        docker compose -f "$COMPOSE_FILE" ps
        ;;
    "update")
        print_status "Pulling latest images..."
        docker compose -f "$COMPOSE_FILE" pull
        docker compose -f "$COMPOSE_FILE" up -d
        print_success "Update complete"
        ;;
    *)
        echo "Usage: $0 {setup|start|stop|restart|logs|status|update}"
        echo ""
        echo "  setup   - First time setup: generate .env and deploy (default)"
        echo "  start   - Start services"
        echo "  stop    - Stop services"
        echo "  restart - Restart services"
        echo "  logs    - View real-time logs"
        echo "  status  - Show service status"
        echo "  update  - Pull latest images and redeploy"
        exit 1
        ;;
esac
