export enum AccountType {
  ASSET = 'Asset',
  LIABILITY = 'Liability',
  EQUITY = 'Equity',
  INCOME = 'Income',
  EXPENSE = 'Expense',
}

export enum PostingType {
  OPENING_BALANCE = 'OPENING_BALANCE',
  SALES_PAYMENT = 'SALES_PAYMENT',
  SALES_FULFILLMENT_REVENUE = 'SALES_FULFILLMENT_REVENUE',
  SALES_FULFILLMENT_COGS = 'SALES_FULFILLMENT_COGS',
  SALES_REFUND = 'SALES_REFUND',
  PURCHASE_PAYMENT = 'PURCHASE_PAYMENT',
  PURCHASE_RECEIVE = 'PURCHASE_RECEIVE',
  PURCHASE_REFUND = 'PURCHASE_REFUND',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',
  EXPENSE_PAYMENT = 'EXPENSE_PAYMENT',
  EXPENSE_REFUND = 'EXPENSE_REFUND',
}

export enum AccountingSourceType {
  SALES_ORDER = 'SALES_ORDER',
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',
  OPENING_BALANCE = 'OPENING_BALANCE',
  EXPENSE = 'EXPENSE',
}

export type PaymentChannel = 'CASH' | 'BANK';
